# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-14 07:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('select', models.TextField(blank=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='usermap',
            options={'ordering': ['-last_modified']},
        ),
        migrations.AlterField(
            model_name='messagerecord',
            name='fr',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='messagerecord',
            name='nl',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='usermap',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='alias',
            name='replace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alias_replace', to='api.MessageRecord'),
        ),
    ]
