# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-23 11:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='metadata',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
