# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-25 08:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_metadata_geometry_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='layerinfo',
            name='layer_id',
        ),
        migrations.RemoveField(
            model_name='layerinfo',
            name='name',
        ),
        migrations.AddField(
            model_name='layerinfo',
            name='metadata_id',
            field=models.UUIDField(default='b676315f-59e9-4378-9142-d0710801493b'),
            preserve_default=False,
        ),
    ]
