# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-10 10:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_layerinfo_legend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermap',
            name='base_layer',
            field=models.CharField(default='urbis.irisnet.be/urbis_gray', max_length=256),
            preserve_default=False,
        ),
    ]
