# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-08 11:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('api', '0008_patch_styles_for_patterns'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermissionGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_map_permission_group', to='auth.Group')),
            ],
        ),
        migrations.AlterField(
            model_name='usermap',
            name='image_url',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='usermap',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='maps', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='permissiongroup',
            name='user_map',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_group_user_map', to='api.UserMap'),
        ),
    ]
