# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-06 09:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20180308_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagerecord',
            name='en',
            field=models.TextField(blank=True),
        ),
    ]
