# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-09-26 10:56
from __future__ import unicode_literals

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_patch_layerinfo_en'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baselayer',
            name='params',
            field=jsonfield.fields.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='layerinfo',
            name='feature_view_options',
            field=jsonfield.fields.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='layerinfo',
            name='style',
            field=jsonfield.fields.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='messagerecord',
            name='parameters',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='keywords',
            field=models.ManyToManyField(blank=True, related_name='md_keyword', to='api.Keyword'),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='topics',
            field=models.ManyToManyField(blank=True, related_name='md_topic', to='api.Topic'),
        ),
    ]
