# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-02-11 14:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20180926_1056'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='link_source', to='api.UserMap')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='link_target', to='api.UserMap')),
            ],
        ),
    ]
