# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-13 10:49
from __future__ import unicode_literals

from django.db import migrations

gemet_data = {
    'http://inspire.ec.europa.eu/theme/br': {
        'fr': 'Conditions atmosphériques',
        'nl': 'Biogeografische gebieden',
    },
    'http://inspire.ec.europa.eu/theme/hb': {
        'fr': 'Installations de suivi environnemental',
        'nl': 'Habitats en biotopen',
    },
    'http://inspire.ec.europa.eu/theme/bu': {
        'fr': 'Régions biogéographiques',
        'nl': 'Gebouwen',
    },
    'http://inspire.ec.europa.eu/theme/hh': {
        'fr': 'Habitats et biotopes',
        'nl': 'Menselijke gezondheid en veiligheid',
    },
    'http://inspire.ec.europa.eu/theme/pd': {
        'fr': 'Caractéristiques géographiques océanographiques',
        'nl': 'Spreiding van de bevolking — demografie',
    },
    'http://inspire.ec.europa.eu/theme/er': {
        'fr': 'Bâtiments',
        'nl': 'Energiebronnen',
    },
    'http://inspire.ec.europa.eu/theme/hy': {
        'fr': 'Dénominations géographiques',
        'nl': 'Hydrografie',
    },
    'http://inspire.ec.europa.eu/theme/mr': {
        'fr': 'Usage des sols',
        'nl': 'Minerale bronnen',
    },
    'http://inspire.ec.europa.eu/theme/sd': {
        'fr': 'Sols',
        'nl': 'Spreiding van soorten',
    },
    'http://inspire.ec.europa.eu/theme/sr': {
        'fr': 'Lieux de production et sites industriels',
        'nl': 'Zeegebieden',
    },
    'http://inspire.ec.europa.eu/theme/so': {
        'fr': 'Régions maritimes',
        'nl': 'Bodem',
    },
    'http://inspire.ec.europa.eu/theme/of': {
        'fr': 'Zones à risque naturel',
        'nl': 'Oceanografische geografische kenmerken',
    },
    'http://inspire.ec.europa.eu/theme/mf': {
        'fr': 'Services d\'utilité publique et services publics',
        'nl': 'Meteorologische geografische kenmerken',
    },
    'http://inspire.ec.europa.eu/theme/su': {
        'fr': 'Répartition des espèces',
        'nl': 'Statistische eenheden',
    },
    'http://inspire.ec.europa.eu/theme/us': {
        'fr': 'Unités statistiques',
        'nl': 'Nutsdiensten en overheidsdiensten',
    },
    'http://inspire.ec.europa.eu/theme/oi': {
        'fr': 'Occupation des terres',
        'nl': 'Orthobeeldvorming',
    },
    'http://inspire.ec.europa.eu/theme/cp': {
        'fr': 'Systèmes de maillage géographique',
        'nl': 'Kadastrale percelen',
    },
    'http://inspire.ec.europa.eu/theme/gn': {
        'fr': 'Parcelles cadastrales',
        'nl': 'Geografische namen',
    },
    'http://inspire.ec.europa.eu/theme/au': {
        'fr': 'Adresses',
        'nl': 'Administratieve eenheden',
    },
    'http://inspire.ec.europa.eu/theme/el': {
        'fr': 'Réseaux de transport',
        'nl': 'Hoogte',
    },
    'http://inspire.ec.europa.eu/theme/ge': {
        'fr': 'Altitude',
        'nl': 'Geologie',
    },
    'http://inspire.ec.europa.eu/theme/gg': {
        'fr': 'Référentiels de coordonnées',
        'nl': 'Geografisch rastersysteem',
    },
    'http://inspire.ec.europa.eu/theme/ef': {
        'fr': 'Sources d\'énergie',
        'nl': 'Milieubewakingsvoorzieningen',
    },
    'http://inspire.ec.europa.eu/theme/am': {
        'fr': 'Installations agricoles et aquacoles',
        'nl': 'Gebiedsbeheer, gebieden waar beperkingen gelden, gereguleerde gebieden en rapportage-eenheden',
    },
    'http://inspire.ec.europa.eu/theme/af': {
        'fr': 'Ortho-imagerie',
        'nl': 'Faciliteiten voor landbouw en aquacultuur',
    },
    'http://inspire.ec.europa.eu/theme/ad': {
        'fr': 'Etiquette',
        'nl': 'Adressen',
    },
    'http://inspire.ec.europa.eu/theme/ac': {
        'fr': 'Zones de gestion, de restriction ou de réglementation et unités de déclaration',
        'nl': 'Atmosferische omstandigheden',
    },
    'http://inspire.ec.europa.eu/theme/lu': {
        'fr': 'Santé et sécurité des personnes',
        'nl': 'Landgebruik',
    },
    'http://inspire.ec.europa.eu/theme/tn': {
        'fr': 'Sites protégés',
        'nl': 'Vervoersnetwerken',
    },
    'http://inspire.ec.europa.eu/theme/nz': {
        'fr': 'Ressources minérales',
        'nl': 'Gebieden met natuurrisico\'s',
    },
    'http://inspire.ec.europa.eu/theme/pf': {
        'fr': 'Répartition de la population — démographie',
        'nl': 'Faciliteiten voor productie en industrie',
    },
    'http://inspire.ec.europa.eu/theme/rs': {
        'fr': 'Unités administratives',
        'nl': 'Systemen voor verwijzing door middel van coördinaten',
    },
    'http://inspire.ec.europa.eu/theme/ps': {
        'fr': 'Hydrographie',
        'nl': 'Beschermde gebieden',
    },
    'http://inspire.ec.europa.eu/theme/ac-mf': {
        'fr': 'Caractéristiques géographiques météorologiques',
        'nl': 'Atmospheric Conditions and meteorological geographical features',
    },
    'http://inspire.ec.europa.eu/theme/lc': {
        'fr': 'Géologie',
        'nl': 'Bodemgebruik',
    },
}

topic_data = {
  "farming": {
    "fr": "agriculture",
    "nl": "landbouw"
  },
  "biota": {
    "fr": "biote",
    "nl": "biota"
  },
  "boundaries": {
    "fr": "limites",
    "nl": "grenzen"
  },
  "climatologyMeteorologyAtmosphere": {
    "fr": "climatologie Météorologie Atmosphère",
    "nl": "klimatologie Meteorologie Atmosfeer"
  },
  "economy": {
    "fr": "économie",
    "nl": "economie"
  },
  "elevation": {
    "fr": "élévation",
    "nl": "verhoging"
  },
  "environment": {
    "fr": "environnement",
    "nl": "milieu"
  },
  "geoscientificInformation": {
    "fr": "Informations géo-scientifiques",
    "nl": "geo wetenschappelijke informatie"
  },
  "health": {
    "fr": "santé",
    "nl": "Gezondheid"
  },
  "imageryBaseMapsEarthCover": {
    "fr": "imagerie BaseMaps Earth Cover",
    "nl": "beeldmateriaal BaseMaps Earth Cover"
  },
  "intelligenceMilitary": {
    "fr": "intelligence militaire",
    "nl": "Intelligentie Militair"
  },
  "inlandWaters": {
    "fr": "eaux intérieures",
    "nl": "binnenwateren"
  },
  "location": {
    "fr": "emplacement",
    "nl": "plaats"
  },
  "oceans": {
    "fr": "océans",
    "nl": "oceanen"
  },
  "planningCadastre": {
    "fr": "planifier le cadastre",
    "nl": "planning Cadastre"
  },
  "society": {
    "fr": "société",
    "nl": "maatschappij"
  },
  "structure": {
    "fr": "structure",
    "nl": "structuur"
  },
  "transportation": {
    "fr": "transport",
    "nl": "vervoer"
  },
  "utilitiesCommunication": {
    "fr": "utilitaires Communication",
    "nl": "utilities Communicatie"
  }
}


def factory(model, db_alias):
    return model.objects.using(db_alias)


def create(model, db_alias, **data):
    return factory(model, db_alias).create(**data)


def create_gemet(thesaurus, message, keyword):
    name = message.create(fr='GEMET', nl='GEMET')
    t = thesaurus.create(
        name=name,
        uri='http://inspire.ec.europa.eu/theme')
    for k, v in gemet_data.items():
        n = message.create(**v)
        keyword.create(thesaurus=t, name=n, code=k)


def create_md_topic(thesaurus, message, topic):
    name = message.create(
        fr='Metadata element - Topic category', 
        nl='Metadata element - Topic category')
    t = thesaurus.create(
        name=name,
        uri='http://inspire.ec.europa.eu/glossary/MetadataElement-TopicCategory')
    for k, v in topic_data.items():
        n = message.create(**v)
        topic.create(thesaurus=t, name=n, code=k)


def forwards_func(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    Thesaurus = apps.get_model("api", "Thesaurus")
    Topic = apps.get_model("api", "Topic")
    Keyword = apps.get_model("api", "Keyword")
    Role = apps.get_model("api", "Role")
    MessageRecord = apps.get_model("api", "MessageRecord")
    db_alias = schema_editor.connection.alias

    thesaurus = factory(Thesaurus, db_alias)
    topic = factory(Topic, db_alias)
    keyword = factory(Keyword, db_alias)
    role = factory(Role, db_alias)
    message = factory(MessageRecord, db_alias)

    create_gemet(thesaurus, message, keyword)
    create_md_topic(thesaurus, message, topic)


def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'), 
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
