# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-15 16:03
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TimeserieRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('schema', models.CharField(max_length=256)),
                ('table', models.CharField(max_length=256)),
                ('time_field', models.CharField(max_length=256)),
                ('value_field', models.CharField(max_length=256)),
                ('quality_field', models.CharField(max_length=256)),
            ],
        ),
    ]
