# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-09 15:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0005_layerinfo_legend'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.CharField(max_length=126, primary_key=True, serialize=False)),
                ('provider', models.URLField()),
                ('version', models.CharField(max_length=6)),
                ('service', models.CharField(choices=[('wms', 'Web Map Service'), ('tms', 'Tile Map Service')], max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='WmsLayer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('crs', models.CharField(max_length=64)),
                ('styles', models.CharField(max_length=1024)),
                ('layers', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wms_layer_layers', to='api.MessageRecord')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wms_layer_name', to='api.MessageRecord')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wms_layers', to='webservice.Service')),
            ],
        ),
    ]
