# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-09 16:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webservice', '0002_auto_20180109_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='wmslayer',
            name='name',
            field=models.CharField(default='layer_name', max_length=126),
            preserve_default=False,
        ),
    ]
