# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-11 09:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webservice', '0003_wmslayer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='password',
            field=models.CharField(blank=True, max_length=126),
        ),
        migrations.AddField(
            model_name='service',
            name='username',
            field=models.CharField(blank=True, max_length=126),
        ),
    ]
