# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-11 15:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('webservice', '0004_auto_20180511_0936'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicePermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_permission_group', to='auth.Group')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_permission_service', to='webservice.Service')),
            ],
        ),
    ]
